# -*- coding: utf-8 -*-
"""Logistics Delivery Performance Analysis Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZktW9OyWo6g69wZntqFv3hI_yroDxzL

# **Logistics Delivery Performance Analysis**

**Objective:**
 Analyze logsitics delivery performance data to identify key affecting delivery speed, efficiency, and agent ratings.

 This project explores delivery times and predictive modeling to improve logistics decision-making.

**Questions**
 - What factors contribute the most to delivery delays (distance, areas, weather)?
- Which areas or categories perform best or worst?
- How do delivery delays impact Agent Ratings?
- Can we predict whether a delivery will be slow?

# **DATA COLLECTION**

Import libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

"""Load Data"""

df = pd.read_csv('/amazon_delivery.csv')

#view the first rows of our dataframe
df.head()

#view our data types and column names
df.info()

#View basic statistics from the dataset
df.describe()

#How many rows and columns does the dataset have?
df.shape

"""# **DATA CLEANING AND WRANGLING**"""

#check for duplicate values
print(df.duplicated().sum())

#Check Missing Values
df.isnull().sum()

#view the median value in AgentRating
AGR_median = df['Agent_Rating'].median()
#view the most frequent value in Weather
Weather_most_frequent_value = df['Weather'].mode()[0]

print ("Most frequent value in AgentRating:", AGR_median)
print ("Most frequent value in Weather:", Weather_most_frequent_value)

#Imput these columns with the most frequent values and its median
df['Agent_Rating'] = df['Agent_Rating'].fillna(AGR_median)
df['Weather'] =df['Weather'].fillna(Weather_most_frequent_value)

#confirm that the nulls were replaced
df.isnull().sum()

"""Normalization"""

#create a new column for normalized agent_ratings with min_max
min_val = df['Agent_Rating'].min()
max_val = df['Agent_Rating'].max()

df['AgentRating_MinMax'] = (df['Agent_Rating'] - min_val) / (max_val - min_val)

#verify the scaling worked
print(df['AgentRating_MinMax'].describe())

"""Feature Engineering"""

#Id like for us to have some sort of distance measure, but it seems we do not have that available, so we will use our longitutde and latitudes

#Using the Haversine formula we will create a distance measure, which is a formula used a lot in logistics

from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):
    R = 6371 #earth's radius  in km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)

    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2))* sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))

    return R * c

#create distance field
df['Distance_in_km'] = df.apply(lambda row: haversine(row['Store_Latitude'], row['Store_Longitude'], row['Drop_Latitude'], row['Drop_Longitude']),axis = 1)
df.head()

#apply log-tranform to distnace
df['Distance_in_km_log'] = np.log1p(df['Distance_in_km'])

#apply z-score to distance_in_km_log for future analysis
mean_val = df['Distance_in_km_log'].mean()
std_val = df['Distance_in_km_log'].std()

df['Distance_Log_Z'] = (df['Distance_in_km_log'] - mean_val) / std_val

"""# **EXPLORATORY DATA ANALYSIS (EDA)**

Analyze Correlations
"""

#view correleation between numeric fields
df[['Distance_in_km', 'Delivery_Time']].corr()

"""Our correlation coefficient of -0.001864, indicates a very weak to almost no linear relationship between the two variables.

In this case it suggests there's no clear pattern indicating that longer distances lead to higher or lower Delivery Times.

Analyzing By Area
"""

#view delivery times by area
df.groupby('Area')['Delivery_Time'].median().sort_values(ascending=False)

sns.barplot(data=df, x='Area', y='Delivery_Time', estimator='median')
plt.title("Median Delivery Time by Area")
plt.show()

"""Our analysis shows a clear difference in delivery across area types. Semi‑Urban areas experience the longest delivery times, with a median of 245 days, making them the slowest‑performing region in the dataset. In contrast, “Other” areas show the shortest delivery times, with a median of 100 days.

This suggests that Semi‑Urban regions may face structural or logistical challenges—such as road conditions, distance from distribution hubs, or limited courier availability.

Analyzing by Type of Weather
"""

df.groupby('Weather')['Delivery_Time'].median().sort_values(ascending = False)

sns.barplot(data=df, x='Weather', y='Delivery_Time', estimator='median')
plt.title("Median Delivery Time by Weather")
plt.xticks(rotation=45)
plt.show()

"""We also seem to see a distinct difference in weather type vs delivery time as well.

Cloudy and Foggy conditions lead to the slowest deliveries, indicating that reduced visibility has a stronger operational impact than more dramatic weather events.

Interestingly, Stormy and Sandstorm conditions do not produce the highest delays, likely because extreme weather reduces the number of active deliveries or prompts companies to adjust routes and schedules.

As expected, Sunny conditions result in the quickest delivery times, reinforcing the idea that clear visibility and stable weather support more efficient operations.

Best/Worst performing Areas and Categories
"""

#Analyzing Area
df.groupby('Area')[['Delivery_Time', 'Agent_Rating']].median().sort_values(by='Delivery_Time', ascending = False)

#Agent ratings are the lowest in semi-urabn areas, this can be expected as they have the highest delivery times meaning delivery times are affected by area and thus affect agent ratings.

#Analze by Category
df.groupby('Category')[['Delivery_Time', 'Agent_Rating']].median().sort_values(by='Delivery_Time', ascending=False)

#Category does not seem to show distinction in agent_ratings

"""Delivery Delays Vs Agent Ratings"""

#Visualize our Agent Ratings
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Agent_Rating', palette='viridis')

plt.title("Distribution of Agent Ratings")
plt.xlabel("Agent Rating")
plt.ylabel("Count")
plt.show()

#Correlation between agent ratings and delivery time
df[['Delivery_Time', 'Agent_Rating']].corr()

#Our corelation coefficient of -0.289855 suggests delivery time does not seem to have too large of an effect on agent-rating

"""However, at what point in delivery_time do we start to see agent ratings start to drop?"""

#split our dleivery-times into groups for better analysis
df['Delay_Group'] = pd.cut(df['Delivery_Time'], bins=[10, 30, 60, 120, 180, 270],labels=['10–30 days', '30–60 days', '60–120 days', '120–180 days', '180–270 days'])

df.groupby('Delay_Group')['Agent_Rating'].median()

sns.boxplot(data=df, x='Delay_Group', y='Agent_Rating')
plt.title("Agent Ratings by Delivery Delay Group")
plt.show()

"""We begin to see agent ratings decline once delivery times exceed 180 days, and when we connect this with our area‑based analysis, a clear pattern emerges: Semi‑Urban areas consistently produce the highest delivery times, with a median around 245 days.

This strongly suggests that Semi‑Urban regions are the primary contributors to delayed deliveries and, in turn, lower agent ratings.

Meaning they should be prioritized for operational improvements if the goal is to raise both delivery speed and agent performance ratings.

# **MODEL TRAINING**
We will now move on to creating our model that will help us predict whether a delivery will be slow based on these features
"""

#First lets make a threshold that qualifies what type of delivery_time will be considered slow.I will choose the top 20% delivery times to be considered slow
threshold = df['Delivery_Time'].quantile(0.80)
df['Slow_Delivery'] = (df['Delivery_Time'] >= threshold).astype(int)

"""Encoding Categorical Values"""

#creating encoded columns
df_model = pd.get_dummies(df[['Distance_in_km', 'Weather', 'Area', 'Category', 'Slow_Delivery']], drop_first=True)

"""Test/train Split"""

X = df_model.drop('Slow_Delivery', axis=1)
y = df_model['Slow_Delivery']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Create our model: Logistic Regression"""

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

"""Evaluate our model"""

y_pred = model.predict(X_test)

#create a classification report
print(classification_report(y_test, y_pred))


#Create our confusion matrix
print(confusion_matrix(y_test, y_pred))

"""The model is very good at identifying non-slow deliveries and is highly accurate when it predicts a delivery will be slow.

However, it struggles with identifying actual slow deliveries, missing a large majority of them.

This means it's a good classifier for confirming a delivery is not slow, but very poor at flagging deliveries that will be slow.

This imbalance in performance is likely due to the class imbalance in our 'Slow_Delivery' target variable (where 'not slow' is the majority class).

Feature Importance
"""

importance = pd.DataFrame({'feature': X.columns, 'coef': model.coef_[0]}).sort_values(by='coef', ascending=False)

#display top 20 feautures that have the most impact on the model's prediction
importance.head(20)

"""Trying a RandomeForest"""

#Create our randomforest
rf = RandomForestClassifier(n_estimators=300, random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
print(classification_report(y_test, rf_pred))

"""Compared to your Logistic Regression model, the Random Forest model shows a trade-off:

Logistic Regression was very good at predicting non-slow deliveries (1.00 recall for '0') and had perfect precision for slow deliveries (1.00 precision for '1'), but it almost never predicted a delivery was slow (0.01 recall for '1'). It was too conservative.

Random Forest is more balanced. While its precision for 'slow' deliveries (0.43) is not perfect, it is much better at actually identifying slow deliveries (0.42 recall for '1') than the Logistic Regression model.

It makes more 'slow' predictions, and a reasonable portion of them are correct.
"""

#What feautures matter the most according to our random forest?
importances = pd.DataFrame({'feature': X.columns,'importance': rf.feature_importances_}).sort_values(by='importance', ascending=False)

importances.head(20)

"""Testing with predictions"""

#Test with a prediction
def predict_delay(weather, area, category, distance):
    row = pd.DataFrame([{
        'Distance_in_km': distance,
        **{col: 1 if col == f"Weather_{weather}" else 0 for col in X.columns if col.startswith("Weather_")},
        **{col: 1 if col == f"Area_{area}" else 0 for col in X.columns if col.startswith("Area_")},
        **{col: 1 if col == f"Category_{category}" else 0 for col in X.columns if col.startswith("Category_")},
    }])
    return rf.predict(row)[0]

predict_delay("Fog", "Urban", "Kitchen", 12.5)

"""## Model Insights

The Random Forest model is a more practical choice if your goal is to identify slow deliveries, even if it means sacrificing some overall accuracy or having some false positives for 'slow' predictions.

It's better at identifying the minority class ('Slow_Delivery') compared to the Logistic Regression model, which was heavily biased towards predicting the majority class ('Not Slow').

The slightly lower overall accuracy is a result of this improved balance in predicting both classes.

# **CONCLUSION**

Overall, our analysis shows that delivery performance is shaped by a combination of geographic and environmental factors, and these patterns directly influence agent ratings.

Semi‑Urban areas consistently produce the longest delivery times, often exceeding 180 minutes, the point at which we begin to see agent ratings decline. This makes Semi‑Urban regions the most critical areas to target for operational improvements.

Weather conditions further reinforce this pattern. Cloudy and Foggy conditions lead to the slowest deliveries, suggesting that visibility challenges have a stronger impact on efficiency than more severe but less frequent conditions like storms or sandstorms.

Our machine‑learning model supports these findings by identifying Area, Weather, and Distance as key predictors of slow deliveries. The model successfully classifies high‑risk deliveries, allowing us to anticipate delays before they occur.

Together, these insights highlight where interventions, such as route optimization, resource allocation, or targeted training,  can have the greatest impact.

By focusing on Semi‑Urban regions and visibility‑related weather conditions, organizations can meaningfully improve both delivery times and agent ratings.
"""